name: tag on old commit
on: 
#  create:
  push:
    tags: 
      - v*
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test
        run: |
          echo test
