name: tag on old commit
on: [gollum]

#  create:
#   push:
#     tags: 
#       - v*
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
      - name: check file
        run: |
          cat README.md
      - uses: y-temp4/add-wip-label@v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"